# Parte 1

1. Crear una matriz de producción ficticia para una empresa que fabrica 3 productos en 2 plantas
2. Convertir la matriz en una tabla de datos
3. Calcular la producción total por planta (suma por filas)
4. Calcular la producción total por producto (suma por columnas)
5. Agregar columnas mediante operaciones que muestren los siguientes atributos: producción total por planta y participación porcentual de cada planta en la producción.
4. Calcular la proyección de una tercer planta que fabricará un 20% más de producto 1 , un 5% más de producto 2 y un 10% más de producto 3 que la primera planta  

In [1]:
# Importaciones
import numpy as np
import pandas as pd

In [2]:
# 1.-Crear una matriz de producción ficticia para una empresa que fabrica 3 productos en 2 plantas
# Crear arrays para cada planta
planta1_produccion = np.array([100, 150, 120])
planta2_produccion = np.array([200, 180, 250])

print("Producción de la Planta 1:")
print(planta1_produccion)

print("\nProducción de la Planta 2:")
print(planta2_produccion)

# Combinar los arrays en una matriz de producción
produccion_matriz = np.array([planta1_produccion, planta2_produccion])

print("\nMatriz de producción:")
print(produccion_matriz)

Producción de la Planta 1:
[100 150 120]

Producción de la Planta 2:
[200 180 250]

Matriz de producción:
[[100 150 120]
 [200 180 250]]


In [3]:
# 2.-Convertir la matriz en una tabla de datos
df = pd.DataFrame(produccion_matriz, columns=['Producto 1', 'Producto 2', 'Producto 3'], index=['Planta 1', 'Planta 2'])
print(df)

          Producto 1  Producto 2  Producto 3
Planta 1         100         150         120
Planta 2         200         180         250


In [4]:
# 3.-Calcular la producción total por planta (suma por filas)
produccion_total_por_planta = df.sum(axis=1)
print("\nProducción total por planta:")
print(produccion_total_por_planta)


Producción total por planta:
Planta 1    370
Planta 2    630
dtype: int64


In [5]:
# 4.-Calcular la producción total por producto (suma por columnas)
produccion_total_por_producto = df.sum(axis=0)
print("\nProducción total por producto:")
print(produccion_total_por_producto)


Producción total por producto:
Producto 1    300
Producto 2    330
Producto 3    370
dtype: int64


In [6]:
# 5.-Agregar columnas mediante operaciones que muestren los siguientes atributos:
# producción total por planta y
# participación porcentual de cada planta en la producción

# Agregar la columna de producción total por planta
df['Producción Total por Planta'] = produccion_total_por_planta

# Calcular la participación porcentual de cada planta
produccion_total_general = produccion_total_por_planta.sum()
df['Participación Porcentual'] = (produccion_total_por_planta / produccion_total_general) * 100

print("\nDataFrame con producción total y participación porcentual:")
print(df)


DataFrame con producción total y participación porcentual:
          Producto 1  Producto 2  Producto 3  Producción Total por Planta  \
Planta 1         100         150         120                          370   
Planta 2         200         180         250                          630   

          Participación Porcentual  
Planta 1                      37.0  
Planta 2                      63.0  


In [7]:
# 6.-Calcular la proyección de una tercer planta que fabricará un 20% más de producto 1,
# un 5% más de producto 2 y un 10% más de producto 3 que la primera planta

# Obtener la producción de la Planta 1
produccion_planta1 = df.loc['Planta 1', ['Producto 1', 'Producto 2', 'Producto 3']]

# Calcular la producción proyectada para la Planta 3
proyeccion_planta3 = produccion_planta1 * np.array([1.20, 1.05, 1.10])

print("\nProducción proyectada para la Planta 3:")
print(proyeccion_planta3)


Producción proyectada para la Planta 3:
Producto 1    120.0
Producto 2    157.5
Producto 3    132.0
Name: Planta 1, dtype: float64
